#!/usr/bin/env bash
exec 2>/dev/null

print_volume() {
  local info volume mute
  info=$(wpctl get-volume @DEFAULT_AUDIO_SINK@) || return
  volume=$(awk '{printf "%d\n", $2 * 100}' <<<"${info}")
  mute=$(grep -F "MUTED" <<<"${info}")

  if [[ -n ${mute} ]]; then
    echo "${volume}% "
  else
    echo "${volume}% "
  fi
}

print_volume

wpctl subscribe | while read -r _; do
  print_volume
done
